"""
PAC name → industry mapping — port of lib/fec-industries.ts
"""
import re

EMPLOYER_INDUSTRY_MAP: dict[str, str] = {
    # Finance & Banking
    "GOLDMAN SACHS": "Finance & Banking",
    "GOLDMAN SACHS & CO": "Finance & Banking",
    "GOLDMAN SACHS & CO.": "Finance & Banking",
    "MORGAN STANLEY": "Finance & Banking",
    "JPMORGAN CHASE": "Finance & Banking",
    "JP MORGAN": "Finance & Banking",
    "JPMORGAN": "Finance & Banking",
    "CITIGROUP": "Finance & Banking",
    "CITIBANK": "Finance & Banking",
    "CITI": "Finance & Banking",
    "BANK OF AMERICA": "Finance & Banking",
    "WELLS FARGO": "Finance & Banking",
    "BARCLAYS": "Finance & Banking",
    "DEUTSCHE BANK": "Finance & Banking",
    "UBS": "Finance & Banking",
    "HSBC": "Finance & Banking",
    "BLACKROCK": "Finance & Banking",
    "FIDELITY INVESTMENTS": "Finance & Banking",
    "VANGUARD GROUP": "Finance & Banking",
    "AMERICAN EXPRESS": "Finance & Banking",
    "CAPITAL ONE": "Finance & Banking",
    "CHARLES SCHWAB": "Finance & Banking",
    "RAYMOND JAMES": "Finance & Banking",
    "MERRILL LYNCH": "Finance & Banking",
    "US BANK": "Finance & Banking",
    "U.S. BANK": "Finance & Banking",
    "PNC FINANCIAL": "Finance & Banking",
    "CITIZENS BANK": "Finance & Banking",
    "SYNCHRONY FINANCIAL": "Finance & Banking",
    "TD BANK": "Finance & Banking",
    "TRUIST": "Finance & Banking",
    "JANNEY MONTGOMERY SCOTT": "Finance & Banking",
    "JANNEY MONTGOMERY SCOTT, LLC": "Finance & Banking",
    "JEFFERIES": "Finance & Banking",
    "NOMURA": "Finance & Banking",
    "PIPER SANDLER": "Finance & Banking",
    "STIFEL": "Finance & Banking",
    "EDWARD JONES": "Finance & Banking",
    # Investment & Private Equity
    "BLACKSTONE": "Investment & Private Equity",
    "KKR": "Investment & Private Equity",
    "KOHLBERG KRAVIS ROBERTS": "Investment & Private Equity",
    "KOHLBERG KRAVIS ROBERTS & CO. L.P.": "Investment & Private Equity",
    "KOHLBERG KRAVIS ROBERTS & CO": "Investment & Private Equity",
    "CARLYLE GROUP": "Investment & Private Equity",
    "APOLLO GLOBAL MANAGEMENT": "Investment & Private Equity",
    "WARBURG PINCUS": "Investment & Private Equity",
    "BAIN CAPITAL": "Investment & Private Equity",
    "GENERAL ATLANTIC": "Investment & Private Equity",
    "ARES MANAGEMENT": "Investment & Private Equity",
    "OAKTREE CAPITAL": "Investment & Private Equity",
    "LAZARD": "Investment & Private Equity",
    "BROOKFIELD ASSET MANAGEMENT": "Investment & Private Equity",
    "CERBERUS CAPITAL MANAGEMENT": "Investment & Private Equity",
    "TPG CAPITAL": "Investment & Private Equity",
    "ADVENT INTERNATIONAL": "Investment & Private Equity",
    "SEQUOIA CAPITAL": "Investment & Private Equity",
    "CITADEL": "Investment & Private Equity",
    "BRIDGEWATER ASSOCIATES": "Investment & Private Equity",
    "RENAISSANCE TECHNOLOGIES": "Investment & Private Equity",
    "TWO SIGMA": "Investment & Private Equity",
    "D.E. SHAW": "Investment & Private Equity",
    # Law
    "PAUL WEISS RIFKIND WHARTON & GARRISON": "Law",
    "PAUL WEISS": "Law",
    "SKADDEN ARPS": "Law",
    "SKADDEN, ARPS, SLATE, MEAGHER & FLOM": "Law",
    "KIRKLAND & ELLIS": "Law",
    "LATHAM & WATKINS": "Law",
    "SULLIVAN & CROMWELL": "Law",
    "SIMPSON THACHER": "Law",
    "SIMPSON THACHER & BARTLETT": "Law",
    "WEIL GOTSHAL": "Law",
    "WEIL GOTSHAL & MANGES": "Law",
    "DEBEVOISE & PLIMPTON": "Law",
    "JONES DAY": "Law",
    "CLEARY GOTTLIEB": "Law",
    "CLEARY GOTTLIEB STEEN & HAMILTON": "Law",
    "GIBSON DUNN": "Law",
    "GIBSON, DUNN & CRUTCHER": "Law",
    "WILMER HALE": "Law",
    "WILMERHALE": "Law",
    "COVINGTON & BURLING": "Law",
    "MAYER BROWN": "Law",
    "SIDLEY AUSTIN": "Law",
    "HOGAN LOVELLS": "Law",
    "WHITE & CASE": "Law",
    "AKIN GUMP": "Law",
    "ARNOLD & PORTER": "Law",
    "MCDERMOTT WILL & EMERY": "Law",
    "FOLEY & LARDNER": "Law",
    "PILLSBURY WINTHROP": "Law",
    "FRAGOMEN DEL REY BERNSEN & LOEWY": "Law",
    "FRAGOMEN DEL REY BERNSEN & LOEWY LLP": "Law",
    "FRAGOMEN, DEL REY, BERNSEN & LOEWY LLP": "Law",
    "CRAVATH SWAINE & MOORE": "Law",
    "PAUL HASTINGS": "Law",
    "ORRICK HERRINGTON": "Law",
    "VINSON & ELKINS": "Law",
    "BAKER BOTTS": "Law",
    "MORGAN LEWIS": "Law",
    "DECHERT": "Law",
    "PROSKAUER ROSE": "Law",
    "STROOCK & STROOCK": "Law",
    # Real Estate
    "RELATED COMPANIES": "Real Estate",
    "VORNADO REALTY": "Real Estate",
    "TISHMAN SPEYER": "Real Estate",
    "EXTELL DEVELOPMENT": "Real Estate",
    "CUSHMAN & WAKEFIELD": "Real Estate",
    "CBRE GROUP": "Real Estate",
    "CBRE": "Real Estate",
    "JLL": "Real Estate",
    "JONES LANG LASALLE": "Real Estate",
    "NEWMARK": "Real Estate",
    "BROOKFIELD PROPERTIES": "Real Estate",
    "BOSTON PROPERTIES": "Real Estate",
    "SL GREEN REALTY": "Real Estate",
    "EQUITY RESIDENTIAL": "Real Estate",
    "AVALONBAY COMMUNITIES": "Real Estate",
    # Healthcare
    "UNITEDHEALTH GROUP": "Healthcare",
    "UNITED HEALTH GROUP": "Healthcare",
    "KAISER PERMANENTE": "Healthcare",
    "AETNA": "Healthcare",
    "CIGNA": "Healthcare",
    "HUMANA": "Healthcare",
    "ANTHEM": "Healthcare",
    "CVS HEALTH": "Healthcare",
    "NORTHWELL HEALTH": "Healthcare",
    "NYU LANGONE HEALTH": "Healthcare",
    "MOUNT SINAI HEALTH SYSTEM": "Healthcare",
    "MEMORIAL SLOAN KETTERING": "Healthcare",
    "COLUMBIA UNIVERSITY IRVING MEDICAL CENTER": "Healthcare",
    "CLEVELAND CLINIC": "Healthcare",
    "MAYO CLINIC": "Healthcare",
    "JOHNS HOPKINS MEDICINE": "Healthcare",
    # Pharmaceuticals
    "PFIZER": "Pharmaceuticals",
    "MERCK": "Pharmaceuticals",
    "JOHNSON & JOHNSON": "Pharmaceuticals",
    "ABBVIE": "Pharmaceuticals",
    "BRISTOL MYERS SQUIBB": "Pharmaceuticals",
    "ELI LILLY": "Pharmaceuticals",
    "AMGEN": "Pharmaceuticals",
    "GILEAD SCIENCES": "Pharmaceuticals",
    "BIOGEN": "Pharmaceuticals",
    "NOVARTIS": "Pharmaceuticals",
    "ASTRAZENECA": "Pharmaceuticals",
    "SANOFI": "Pharmaceuticals",
    "BAYER": "Pharmaceuticals",
    "ROCHE": "Pharmaceuticals",
    "GENENTECH": "Pharmaceuticals",
    "MODERNA": "Pharmaceuticals",
    # Technology
    "GOOGLE": "Technology",
    "ALPHABET INC": "Technology",
    "MICROSOFT": "Technology",
    "APPLE INC": "Technology",
    "APPLE": "Technology",
    "AMAZON": "Technology",
    "META": "Technology",
    "FACEBOOK": "Technology",
    "TWITTER": "Technology",
    "NETFLIX": "Technology",
    "SALESFORCE": "Technology",
    "ORACLE": "Technology",
    "IBM": "Technology",
    "INTEL": "Technology",
    "NVIDIA": "Technology",
    "QUALCOMM": "Technology",
    "CISCO": "Technology",
    "HP INC": "Technology",
    "DELL": "Technology",
    "AIRBNB": "Technology",
    "UBER": "Technology",
    "LYFT": "Technology",
    "SPOTIFY": "Technology",
    "LINKEDIN": "Technology",
    "SNAP INC": "Technology",
    "PALANTIR TECHNOLOGIES": "Technology",
    "CLOUDFLARE": "Technology",
    "STRIPE": "Technology",
    "COINBASE": "Technology",
    "CORNING INCORPORATED": "Technology",
    "CORNING": "Technology",
    # Energy
    "NEXTERA ENERGY": "Energy",
    "EXXONMOBIL": "Energy",
    "CHEVRON": "Energy",
    "CONOCOPHILLIPS": "Energy",
    "SHELL OIL": "Energy",
    "BP": "Energy",
    "HALLIBURTON": "Energy",
    "BAKER HUGHES": "Energy",
    "SCHLUMBERGER": "Energy",
    "DUKE ENERGY": "Energy",
    "DOMINION ENERGY": "Energy",
    "SOUTHERN COMPANY": "Energy",
    "XCEL ENERGY": "Energy",
    "ENTERGY": "Energy",
    "CONSOLIDATED EDISON": "Energy",
    "CON EDISON": "Energy",
    "PG&E": "Energy",
    "AMERICAN ELECTRIC POWER": "Energy",
    "FIRSTENERGY": "Energy",
    "VALERO ENERGY": "Energy",
    "MARATHON OIL": "Energy",
    "DEVON ENERGY": "Energy",
    "PIONEER NATURAL RESOURCES": "Energy",
    # Defense
    "LOCKHEED MARTIN": "Defense",
    "RAYTHEON": "Defense",
    "BOEING": "Defense",
    "NORTHROP GRUMMAN": "Defense",
    "GENERAL DYNAMICS": "Defense",
    "L3 TECHNOLOGIES": "Defense",
    "LEIDOS": "Defense",
    "SAIC": "Defense",
    "BOOZ ALLEN HAMILTON": "Defense",
    "TEXTRON": "Defense",
    "BAE SYSTEMS": "Defense",
    "HARRIS CORPORATION": "Defense",
    "L3HARRIS TECHNOLOGIES": "Defense",
    # Media & Entertainment
    "COMCAST": "Media & Entertainment",
    "NBCUNIVERSAL": "Media & Entertainment",
    "NBC UNIVERSAL": "Media & Entertainment",
    "DISNEY": "Media & Entertainment",
    "WALT DISNEY COMPANY": "Media & Entertainment",
    "NEWS CORP": "Media & Entertainment",
    "FOX CORPORATION": "Media & Entertainment",
    "TIME WARNER": "Media & Entertainment",
    "CBS": "Media & Entertainment",
    "NEW YORK TIMES": "Media & Entertainment",
    "VIACOMCBS": "Media & Entertainment",
    "PARAMOUNT": "Media & Entertainment",
    "WARNER BROS": "Media & Entertainment",
    "DISCOVERY INC": "Media & Entertainment",
    "WASHINGTON POST": "Media & Entertainment",
    "CONDE NAST": "Media & Entertainment",
    "HEARST": "Media & Entertainment",
    # Education
    "HARVARD UNIVERSITY": "Education",
    "YALE UNIVERSITY": "Education",
    "COLUMBIA UNIVERSITY": "Education",
    "STANFORD UNIVERSITY": "Education",
    "MIT": "Education",
    "NEW YORK UNIVERSITY": "Education",
    "NYU": "Education",
    "GEORGETOWN UNIVERSITY": "Education",
    "GEORGE WASHINGTON UNIVERSITY": "Education",
    "UNIVERSITY OF PENNSYLVANIA": "Education",
    "PRINCETON UNIVERSITY": "Education",
    "DUKE UNIVERSITY": "Education",
    "UNIVERSITY OF CHICAGO": "Education",
    "UNIVERSITY OF MICHIGAN": "Education",
    "UNIVERSITY OF CALIFORNIA": "Education",
    # Consulting
    "MCKINSEY & COMPANY": "Consulting",
    "MCKINSEY": "Consulting",
    "BCG": "Consulting",
    "BOSTON CONSULTING GROUP": "Consulting",
    "DELOITTE": "Consulting",
    "ERNST & YOUNG": "Consulting",
    "EY": "Consulting",
    "PRICEWATERHOUSECOOPERS": "Consulting",
    "PWC": "Consulting",
    "KPMG": "Consulting",
    "ACCENTURE": "Consulting",
    "OLIVER WYMAN": "Consulting",
    "BAIN & COMPANY": "Consulting",
    "A.T. KEARNEY": "Consulting",
    # Transportation
    "UNITED AIRLINES": "Transportation",
    "AMERICAN AIRLINES": "Transportation",
    "DELTA AIR LINES": "Transportation",
    "SOUTHWEST AIRLINES": "Transportation",
    "JETBLUE": "Transportation",
    "AMTRAK": "Transportation",
    "CSX": "Transportation",
    "NORFOLK SOUTHERN": "Transportation",
    "UNION PACIFIC": "Transportation",
    "FEDEX": "Transportation",
    "UPS": "Transportation",
    "DHL": "Transportation",
    # Retail & Commerce
    "WALMART": "Retail & Commerce",
    "TARGET": "Retail & Commerce",
    "HOME DEPOT": "Retail & Commerce",
    "COSTCO": "Retail & Commerce",
    "MACY'S": "Retail & Commerce",
    "NORDSTROM": "Retail & Commerce",
    "WALGREENS": "Retail & Commerce",
    "KROGER": "Retail & Commerce",
    "WHOLE FOODS MARKET": "Retail & Commerce",
}

INDUSTRY_KEYWORD_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"INVEST|ASSET MGMT|HEDGE FUND|PRIVATE EQUITY"), "Investment & Private Equity"),
    (re.compile(r"BANK|FINANCIAL|FINANCE|CREDIT UNION|MORTGAGE|BROKERAGE|SECURITIES"), "Finance & Banking"),
    (re.compile(r"\bLAW\b|LLP|ATTORNEYS|LEGAL|COUNSEL|SOLICITORS"), "Law"),
    (re.compile(r"REALT|REAL ESTATE|HOMEBUIL"), "Real Estate"),
    (re.compile(r"PHARMA|BIOTECH|BIOSCIENCE|THERAPEUTICS|GENOMICS"), "Pharmaceuticals"),
    (re.compile(r"HEALTH|HOSPITAL|MEDICAL|CLINIC|DENTAL|SURGERY"), "Healthcare"),
    (re.compile(r"TECH|SOFTWARE|DIGITAL|CYBER|CLOUD|PLATFORM"), "Technology"),
    (re.compile(r"ENERGY|OIL|GAS|PETROLEUM|POWER|ELECTRIC|UTILITY|SOLAR|WIND"), "Energy"),
    (re.compile(r"DEFENSE|AEROSPACE|ARMAMENT"), "Defense"),
    (re.compile(r"UNIVERSITY|COLLEGE|SCHOOL|ACADEMY|INSTITUTE OF"), "Education"),
    (re.compile(r"MEDIA|BROADCAST|PUBLISH|ENTERTAINMENT|STUDIO|FILM|TELEVISION"), "Media & Entertainment"),
    (re.compile(r"AIRLINE|AIRWAYS|RAIL|RAILROAD|SHIPPING|TRANSPORT|LOGISTICS"), "Transportation"),
    (re.compile(r"CONSULT|ADVISORY|MANAGEMENT SOLUTIONS"), "Consulting"),
    (re.compile(r"HOTEL|RESORT|HOSPITALITY|RESTAURANT|FOOD SERVICE"), "Hospitality & Food"),
    (re.compile(r"CAPITAL"), "Investment & Private Equity"),
    (re.compile(r"GOVERNMENT|FEDERAL|STATE OF |COUNTY OF |CITY OF |DEPT OF "), "Government & Public Sector"),
]

# Maps FEC/employer industry categories to bill topic slugs for pre-filtering
INDUSTRY_TO_TOPICS: dict[str, list[str]] = {
    "Energy":                      ["climate-environment", "economy-jobs"],
    "Healthcare":                  ["healthcare"],
    "Pharmaceuticals":             ["healthcare"],
    "Technology":                  ["tech-privacy", "economy-jobs"],
    "Finance & Banking":           ["economy-jobs"],
    "Investment & Private Equity": ["economy-jobs"],
    "Defense":                     ["foreign-policy"],
    "Education":                   ["education"],
    "Real Estate":                 ["housing", "economy-jobs"],
    "Media & Entertainment":       ["tech-privacy"],
    "Transportation":              ["economy-jobs"],
    "Consulting":                  [],
    "Law":                         [],
    "Government & Public Sector":  [],
    "Hospitality & Food":          ["economy-jobs"],
    "Various":                     [],
}


def get_employer_industry(raw_uppercase_name: str) -> str:
    key = raw_uppercase_name.upper().strip()
    if key in EMPLOYER_INDUSTRY_MAP:
        return EMPLOYER_INDUSTRY_MAP[key]
    for pattern, industry in INDUSTRY_KEYWORD_PATTERNS:
        if pattern.search(key):
            return industry
    return "Various"
