// This file is auto-generated by TanStack Router plugin
// Run `pnpm dev` to regenerate
import { Route as rootRoute } from "./routes/__root";
import { Route as indexRoute } from "./routes/index";

export const routeTree = rootRoute.addChildren([indexRoute]);
