/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedRepresentativesIndexRouteImport } from './routes/_authenticated/representatives/index'
import { Route as AuthenticatedDonorsIndexRouteImport } from './routes/_authenticated/donors/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedRepresentativesIdRouteImport } from './routes/_authenticated/representatives/$id'
import { Route as AuthenticatedDonorsCmteIdRouteImport } from './routes/_authenticated/donors/$cmteId'
import { Route as AuthenticatedBillsBillIdIndexRouteImport } from './routes/_authenticated/bills/$billId/index'
import { Route as AuthenticatedBillsBillIdVotesVoteIdRouteImport } from './routes/_authenticated/bills/$billId/votes/$voteId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepresentativesIndexRoute =
  AuthenticatedRepresentativesIndexRouteImport.update({
    id: '/representatives/',
    path: '/representatives/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsIndexRoute =
  AuthenticatedDonorsIndexRouteImport.update({
    id: '/donors/',
    path: '/donors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepresentativesIdRoute =
  AuthenticatedRepresentativesIdRouteImport.update({
    id: '/representatives/$id',
    path: '/representatives/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsCmteIdRoute =
  AuthenticatedDonorsCmteIdRouteImport.update({
    id: '/donors/$cmteId',
    path: '/donors/$cmteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsBillIdIndexRoute =
  AuthenticatedBillsBillIdIndexRouteImport.update({
    id: '/bills/$billId/',
    path: '/bills/$billId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsBillIdVotesVoteIdRoute =
  AuthenticatedBillsBillIdVotesVoteIdRouteImport.update({
    id: '/bills/$billId/votes/$voteId',
    path: '/bills/$billId/votes/$voteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/donors/$cmteId': typeof AuthenticatedDonorsCmteIdRoute
  '/representatives/$id': typeof AuthenticatedRepresentativesIdRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/donors/': typeof AuthenticatedDonorsIndexRoute
  '/representatives/': typeof AuthenticatedRepresentativesIndexRoute
  '/bills/$billId/': typeof AuthenticatedBillsBillIdIndexRoute
  '/bills/$billId/votes/$voteId': typeof AuthenticatedBillsBillIdVotesVoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/donors/$cmteId': typeof AuthenticatedDonorsCmteIdRoute
  '/representatives/$id': typeof AuthenticatedRepresentativesIdRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/donors': typeof AuthenticatedDonorsIndexRoute
  '/representatives': typeof AuthenticatedRepresentativesIndexRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdIndexRoute
  '/bills/$billId/votes/$voteId': typeof AuthenticatedBillsBillIdVotesVoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_authenticated/donors/$cmteId': typeof AuthenticatedDonorsCmteIdRoute
  '/_authenticated/representatives/$id': typeof AuthenticatedRepresentativesIdRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/donors/': typeof AuthenticatedDonorsIndexRoute
  '/_authenticated/representatives/': typeof AuthenticatedRepresentativesIndexRoute
  '/_authenticated/bills/$billId/': typeof AuthenticatedBillsBillIdIndexRoute
  '/_authenticated/bills/$billId/votes/$voteId': typeof AuthenticatedBillsBillIdVotesVoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/settings'
    | '/auth/$pathname'
    | '/donors/$cmteId'
    | '/representatives/$id'
    | '/bills/'
    | '/donors/'
    | '/representatives/'
    | '/bills/$billId/'
    | '/bills/$billId/votes/$voteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/settings'
    | '/auth/$pathname'
    | '/donors/$cmteId'
    | '/representatives/$id'
    | '/bills'
    | '/donors'
    | '/representatives'
    | '/bills/$billId'
    | '/bills/$billId/votes/$voteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/auth/$pathname'
    | '/_authenticated/donors/$cmteId'
    | '/_authenticated/representatives/$id'
    | '/_authenticated/bills/'
    | '/_authenticated/donors/'
    | '/_authenticated/representatives/'
    | '/_authenticated/bills/$billId/'
    | '/_authenticated/bills/$billId/votes/$voteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/representatives/': {
      id: '/_authenticated/representatives/'
      path: '/representatives'
      fullPath: '/representatives/'
      preLoaderRoute: typeof AuthenticatedRepresentativesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/': {
      id: '/_authenticated/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthenticatedDonorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/representatives/$id': {
      id: '/_authenticated/representatives/$id'
      path: '/representatives/$id'
      fullPath: '/representatives/$id'
      preLoaderRoute: typeof AuthenticatedRepresentativesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/$cmteId': {
      id: '/_authenticated/donors/$cmteId'
      path: '/donors/$cmteId'
      fullPath: '/donors/$cmteId'
      preLoaderRoute: typeof AuthenticatedDonorsCmteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/$billId/': {
      id: '/_authenticated/bills/$billId/'
      path: '/bills/$billId'
      fullPath: '/bills/$billId/'
      preLoaderRoute: typeof AuthenticatedBillsBillIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/$billId/votes/$voteId': {
      id: '/_authenticated/bills/$billId/votes/$voteId'
      path: '/bills/$billId/votes/$voteId'
      fullPath: '/bills/$billId/votes/$voteId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdVotesVoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDonorsCmteIdRoute: typeof AuthenticatedDonorsCmteIdRoute
  AuthenticatedRepresentativesIdRoute: typeof AuthenticatedRepresentativesIdRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedDonorsIndexRoute: typeof AuthenticatedDonorsIndexRoute
  AuthenticatedRepresentativesIndexRoute: typeof AuthenticatedRepresentativesIndexRoute
  AuthenticatedBillsBillIdIndexRoute: typeof AuthenticatedBillsBillIdIndexRoute
  AuthenticatedBillsBillIdVotesVoteIdRoute: typeof AuthenticatedBillsBillIdVotesVoteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDonorsCmteIdRoute: AuthenticatedDonorsCmteIdRoute,
  AuthenticatedRepresentativesIdRoute: AuthenticatedRepresentativesIdRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedDonorsIndexRoute: AuthenticatedDonorsIndexRoute,
  AuthenticatedRepresentativesIndexRoute:
    AuthenticatedRepresentativesIndexRoute,
  AuthenticatedBillsBillIdIndexRoute: AuthenticatedBillsBillIdIndexRoute,
  AuthenticatedBillsBillIdVotesVoteIdRoute:
    AuthenticatedBillsBillIdVotesVoteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
