'use client'

/**
 * Application-wide error boundary.
 *
 * `global-error.tsx` is Next.js's last line of defense — it catches errors
 * thrown in the root layout itself, where no other `error.tsx` boundary can
 * reach. Because it replaces the root layout, it MUST render its own
 * `<html>` and `<body>` tags.
 *
 * Important constraints:
 *   - Tailwind utility classes and `globals.css` are NOT available here (the
 *     failing layout is what loads them). Styles must be inline.
 *   - External runtime dependencies should be avoided — this file has to
 *     render even if application code is in a broken state.
 *   - Any observability hook (Sentry, etc.) should be wired up in the
 *     `useEffect` below so it only runs on the client.
 */

import { useEffect } from 'react'

interface GlobalErrorProps {
  error: Error & { digest?: string }
  /** Re-runs the failed segment. Safe to call multiple times. */
  reset: () => void
}

export default function GlobalError({ error, reset }: GlobalErrorProps) {
  useEffect(() => {
    // Hook point for error reporting services. Intentionally a no-op today.
    // Example:  Sentry.captureException(error)
    // The `digest` field is a stable id generated by Next.js for a given
    // server error and is the recommended key for correlating client reports
    // with server logs.
    if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.error('[GlobalError]', error)
    }
  }, [error])

  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          background: '#F5F0E8',
          fontFamily: 'Inter, sans-serif',
        }}
      >
        <div
          style={{
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '0 24px',
            textAlign: 'center',
          }}
        >
          <p
            style={{
              fontSize: 72,
              fontWeight: 700,
              color: 'rgba(155,127,166,0.2)',
              lineHeight: 1,
              marginBottom: 8,
              userSelect: 'none',
            }}
          >
            500
          </p>
          <h1
            style={{
              fontSize: 22,
              fontWeight: 600,
              color: '#1C1C1A',
              marginBottom: 10,
              marginTop: 0,
            }}
          >
            Something went wrong
          </h1>
          <p
            style={{
              fontSize: 14,
              color: 'rgba(28,28,26,0.55)',
              marginBottom: 28,
              lineHeight: 1.6,
            }}
          >
            An unexpected error occurred. Please try again.
            {error.digest && (
              <span
                style={{
                  display: 'block',
                  marginTop: 6,
                  fontSize: 11,
                  color: 'rgba(28,28,26,0.35)',
                  fontFamily: 'monospace',
                }}
              >
                Error ID: {error.digest}
              </span>
            )}
          </p>
          <div style={{ display: 'flex', gap: 12 }}>
            <button
              type="button"
              onClick={reset}
              style={{
                padding: '10px 20px',
                background: '#7B5E8A',
                color: '#fff',
                border: 'none',
                borderRadius: 8,
                fontSize: 14,
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Try again
            </button>
            {/* Plain <a> is intentional — global-error must render without Next.js primitives. */}
            {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
            <a
              href="/"
              style={{
                padding: '10px 20px',
                background: 'transparent',
                color: '#1C1C1A',
                border: '1px solid rgba(28,28,26,0.2)',
                borderRadius: 8,
                fontSize: 14,
                fontWeight: 500,
                textDecoration: 'none',
                display: 'inline-block',
              }}
            >
              Go home
            </a>
          </div>
        </div>
      </body>
    </html>
  )
}
