const EMPLOYER_INDUSTRY_MAP: Record<string, string> = {
  // Finance & Banking
  'GOLDMAN SACHS': 'Finance & Banking',
  'GOLDMAN SACHS & CO': 'Finance & Banking',
  'GOLDMAN SACHS & CO.': 'Finance & Banking',
  'MORGAN STANLEY': 'Finance & Banking',
  'JPMORGAN CHASE': 'Finance & Banking',
  'JP MORGAN': 'Finance & Banking',
  'JPMORGAN': 'Finance & Banking',
  'CITIGROUP': 'Finance & Banking',
  'CITIBANK': 'Finance & Banking',
  'CITI': 'Finance & Banking',
  'BANK OF AMERICA': 'Finance & Banking',
  'WELLS FARGO': 'Finance & Banking',
  'BARCLAYS': 'Finance & Banking',
  'DEUTSCHE BANK': 'Finance & Banking',
  'UBS': 'Finance & Banking',
  'HSBC': 'Finance & Banking',
  'BLACKROCK': 'Finance & Banking',
  'FIDELITY INVESTMENTS': 'Finance & Banking',
  'VANGUARD GROUP': 'Finance & Banking',
  'AMERICAN EXPRESS': 'Finance & Banking',
  'CAPITAL ONE': 'Finance & Banking',
  'CHARLES SCHWAB': 'Finance & Banking',
  'RAYMOND JAMES': 'Finance & Banking',
  'MERRILL LYNCH': 'Finance & Banking',
  'US BANK': 'Finance & Banking',
  'U.S. BANK': 'Finance & Banking',
  'PNC FINANCIAL': 'Finance & Banking',
  'CITIZENS BANK': 'Finance & Banking',
  'SYNCHRONY FINANCIAL': 'Finance & Banking',
  'TD BANK': 'Finance & Banking',
  'TRUIST': 'Finance & Banking',
  'JANNEY MONTGOMERY SCOTT': 'Finance & Banking',
  'JANNEY MONTGOMERY SCOTT, LLC': 'Finance & Banking',
  'JEFFERIES': 'Finance & Banking',
  'NOMURA': 'Finance & Banking',
  'PIPER SANDLER': 'Finance & Banking',
  'STIFEL': 'Finance & Banking',
  'EDWARD JONES': 'Finance & Banking',

  // Investment & Private Equity
  'BLACKSTONE': 'Investment & Private Equity',
  'KKR': 'Investment & Private Equity',
  'KOHLBERG KRAVIS ROBERTS': 'Investment & Private Equity',
  'KOHLBERG KRAVIS ROBERTS & CO. L.P.': 'Investment & Private Equity',
  'KOHLBERG KRAVIS ROBERTS & CO': 'Investment & Private Equity',
  'CARLYLE GROUP': 'Investment & Private Equity',
  'APOLLO GLOBAL MANAGEMENT': 'Investment & Private Equity',
  'WARBURG PINCUS': 'Investment & Private Equity',
  'BAIN CAPITAL': 'Investment & Private Equity',
  'GENERAL ATLANTIC': 'Investment & Private Equity',
  'ARES MANAGEMENT': 'Investment & Private Equity',
  'OAKTREE CAPITAL': 'Investment & Private Equity',
  'LAZARD': 'Investment & Private Equity',
  'BROOKFIELD ASSET MANAGEMENT': 'Investment & Private Equity',
  'CERBERUS CAPITAL MANAGEMENT': 'Investment & Private Equity',
  'TPG CAPITAL': 'Investment & Private Equity',
  'ADVENT INTERNATIONAL': 'Investment & Private Equity',
  'SEQUOIA CAPITAL': 'Investment & Private Equity',
  'CITADEL': 'Investment & Private Equity',
  'BRIDGEWATER ASSOCIATES': 'Investment & Private Equity',
  'RENAISSANCE TECHNOLOGIES': 'Investment & Private Equity',
  'TWO SIGMA': 'Investment & Private Equity',
  'D.E. SHAW': 'Investment & Private Equity',

  // Law
  'PAUL WEISS RIFKIND WHARTON & GARRISON': 'Law',
  'PAUL WEISS': 'Law',
  'SKADDEN ARPS': 'Law',
  'SKADDEN, ARPS, SLATE, MEAGHER & FLOM': 'Law',
  'KIRKLAND & ELLIS': 'Law',
  'LATHAM & WATKINS': 'Law',
  'SULLIVAN & CROMWELL': 'Law',
  'SIMPSON THACHER': 'Law',
  'SIMPSON THACHER & BARTLETT': 'Law',
  'WEIL GOTSHAL': 'Law',
  'WEIL GOTSHAL & MANGES': 'Law',
  'DEBEVOISE & PLIMPTON': 'Law',
  'JONES DAY': 'Law',
  'CLEARY GOTTLIEB': 'Law',
  'CLEARY GOTTLIEB STEEN & HAMILTON': 'Law',
  'GIBSON DUNN': 'Law',
  'GIBSON, DUNN & CRUTCHER': 'Law',
  'WILMER HALE': 'Law',
  'WILMERHALE': 'Law',
  'COVINGTON & BURLING': 'Law',
  'MAYER BROWN': 'Law',
  'SIDLEY AUSTIN': 'Law',
  'HOGAN LOVELLS': 'Law',
  'WHITE & CASE': 'Law',
  'AKIN GUMP': 'Law',
  'ARNOLD & PORTER': 'Law',
  'MCDERMOTT WILL & EMERY': 'Law',
  'FOLEY & LARDNER': 'Law',
  'PILLSBURY WINTHROP': 'Law',
  'FRAGOMEN DEL REY BERNSEN & LOEWY': 'Law',
  'FRAGOMEN DEL REY BERNSEN & LOEWY LLP': 'Law',
  'FRAGOMEN, DEL REY, BERNSEN & LOEWY LLP': 'Law',
  'CRAVATH SWAINE & MOORE': 'Law',
  'PAUL HASTINGS': 'Law',
  'ORRICK HERRINGTON': 'Law',
  'VINSON & ELKINS': 'Law',
  'BAKER BOTTS': 'Law',
  'MORGAN LEWIS': 'Law',
  'DECHERT': 'Law',
  'PROSKAUER ROSE': 'Law',
  'STROOCK & STROOCK': 'Law',

  // Real Estate
  'RELATED COMPANIES': 'Real Estate',
  'VORNADO REALTY': 'Real Estate',
  'TISHMAN SPEYER': 'Real Estate',
  'EXTELL DEVELOPMENT': 'Real Estate',
  'CUSHMAN & WAKEFIELD': 'Real Estate',
  'CBRE GROUP': 'Real Estate',
  'CBRE': 'Real Estate',
  'JLL': 'Real Estate',
  'JONES LANG LASALLE': 'Real Estate',
  'NEWMARK': 'Real Estate',
  'BROOKFIELD PROPERTIES': 'Real Estate',
  'BOSTON PROPERTIES': 'Real Estate',
  'SL GREEN REALTY': 'Real Estate',
  'EQUITY RESIDENTIAL': 'Real Estate',
  'AVALONBAY COMMUNITIES': 'Real Estate',

  // Healthcare
  'UNITEDHEALTH GROUP': 'Healthcare',
  'UNITED HEALTH GROUP': 'Healthcare',
  'KAISER PERMANENTE': 'Healthcare',
  'AETNA': 'Healthcare',
  'CIGNA': 'Healthcare',
  'HUMANA': 'Healthcare',
  'ANTHEM': 'Healthcare',
  'CVS HEALTH': 'Healthcare',
  'NORTHWELL HEALTH': 'Healthcare',
  'NYU LANGONE HEALTH': 'Healthcare',
  'MOUNT SINAI HEALTH SYSTEM': 'Healthcare',
  'MEMORIAL SLOAN KETTERING': 'Healthcare',
  'COLUMBIA UNIVERSITY IRVING MEDICAL CENTER': 'Healthcare',
  'CLEVELAND CLINIC': 'Healthcare',
  'MAYO CLINIC': 'Healthcare',
  'JOHNS HOPKINS MEDICINE': 'Healthcare',

  // Pharmaceuticals
  'PFIZER': 'Pharmaceuticals',
  'MERCK': 'Pharmaceuticals',
  'JOHNSON & JOHNSON': 'Pharmaceuticals',
  'ABBVIE': 'Pharmaceuticals',
  'BRISTOL MYERS SQUIBB': 'Pharmaceuticals',
  'ELI LILLY': 'Pharmaceuticals',
  'AMGEN': 'Pharmaceuticals',
  'GILEAD SCIENCES': 'Pharmaceuticals',
  'BIOGEN': 'Pharmaceuticals',
  'NOVARTIS': 'Pharmaceuticals',
  'ASTRAZENECA': 'Pharmaceuticals',
  'SANOFI': 'Pharmaceuticals',
  'BAYER': 'Pharmaceuticals',
  'ROCHE': 'Pharmaceuticals',
  'GENENTECH': 'Pharmaceuticals',
  'MODERNA': 'Pharmaceuticals',

  // Technology
  'GOOGLE': 'Technology',
  'ALPHABET INC': 'Technology',
  'MICROSOFT': 'Technology',
  'APPLE INC': 'Technology',
  'APPLE': 'Technology',
  'AMAZON': 'Technology',
  'META': 'Technology',
  'FACEBOOK': 'Technology',
  'TWITTER': 'Technology',
  'NETFLIX': 'Technology',
  'SALESFORCE': 'Technology',
  'ORACLE': 'Technology',
  'IBM': 'Technology',
  'INTEL': 'Technology',
  'NVIDIA': 'Technology',
  'QUALCOMM': 'Technology',
  'CISCO': 'Technology',
  'HP INC': 'Technology',
  'DELL': 'Technology',
  'AIRBNB': 'Technology',
  'UBER': 'Technology',
  'LYFT': 'Technology',
  'SPOTIFY': 'Technology',
  'LINKEDIN': 'Technology',
  'SNAP INC': 'Technology',
  'PALANTIR TECHNOLOGIES': 'Technology',
  'CLOUDFLARE': 'Technology',
  'STRIPE': 'Technology',
  'COINBASE': 'Technology',
  'CORNING INCORPORATED': 'Technology',
  'CORNING': 'Technology',

  // Energy
  'NEXTERA ENERGY': 'Energy',
  'EXXONMOBIL': 'Energy',
  'CHEVRON': 'Energy',
  'CONOCOPHILLIPS': 'Energy',
  'SHELL OIL': 'Energy',
  'BP': 'Energy',
  'HALLIBURTON': 'Energy',
  'BAKER HUGHES': 'Energy',
  'SCHLUMBERGER': 'Energy',
  'DUKE ENERGY': 'Energy',
  'DOMINION ENERGY': 'Energy',
  'SOUTHERN COMPANY': 'Energy',
  'XCEL ENERGY': 'Energy',
  'ENTERGY': 'Energy',
  'CONSOLIDATED EDISON': 'Energy',
  'CON EDISON': 'Energy',
  'PG&E': 'Energy',
  'AMERICAN ELECTRIC POWER': 'Energy',
  'FIRSTENERGY': 'Energy',
  'VALERO ENERGY': 'Energy',
  'MARATHON OIL': 'Energy',
  'DEVON ENERGY': 'Energy',
  'PIONEER NATURAL RESOURCES': 'Energy',

  // Defense
  'LOCKHEED MARTIN': 'Defense',
  'RAYTHEON': 'Defense',
  'BOEING': 'Defense',
  'NORTHROP GRUMMAN': 'Defense',
  'GENERAL DYNAMICS': 'Defense',
  'L3 TECHNOLOGIES': 'Defense',
  'LEIDOS': 'Defense',
  'SAIC': 'Defense',
  'BOOZ ALLEN HAMILTON': 'Defense',
  'TEXTRON': 'Defense',
  'BAE SYSTEMS': 'Defense',
  'HARRIS CORPORATION': 'Defense',
  'L3HARRIS TECHNOLOGIES': 'Defense',

  // Media & Entertainment
  'COMCAST': 'Media & Entertainment',
  'NBCUNIVERSAL': 'Media & Entertainment',
  'NBC UNIVERSAL': 'Media & Entertainment',
  'DISNEY': 'Media & Entertainment',
  'WALT DISNEY COMPANY': 'Media & Entertainment',
  'NEWS CORP': 'Media & Entertainment',
  'FOX CORPORATION': 'Media & Entertainment',
  'TIME WARNER': 'Media & Entertainment',
  'CBS': 'Media & Entertainment',
  'NEW YORK TIMES': 'Media & Entertainment',
  'VIACOMCBS': 'Media & Entertainment',
  'PARAMOUNT': 'Media & Entertainment',
  'WARNER BROS': 'Media & Entertainment',
  'DISCOVERY INC': 'Media & Entertainment',
  'WASHINGTON POST': 'Media & Entertainment',
  'CONDE NAST': 'Media & Entertainment',
  'HEARST': 'Media & Entertainment',

  // Education
  'HARVARD UNIVERSITY': 'Education',
  'YALE UNIVERSITY': 'Education',
  'COLUMBIA UNIVERSITY': 'Education',
  'STANFORD UNIVERSITY': 'Education',
  'MIT': 'Education',
  'NEW YORK UNIVERSITY': 'Education',
  'NYU': 'Education',
  'GEORGETOWN UNIVERSITY': 'Education',
  'GEORGE WASHINGTON UNIVERSITY': 'Education',
  'UNIVERSITY OF PENNSYLVANIA': 'Education',
  'PRINCETON UNIVERSITY': 'Education',
  'DUKE UNIVERSITY': 'Education',
  'UNIVERSITY OF CHICAGO': 'Education',
  'UNIVERSITY OF MICHIGAN': 'Education',
  'UNIVERSITY OF CALIFORNIA': 'Education',

  // Consulting
  'MCKINSEY & COMPANY': 'Consulting',
  'MCKINSEY': 'Consulting',
  'BCG': 'Consulting',
  'BOSTON CONSULTING GROUP': 'Consulting',
  'DELOITTE': 'Consulting',
  'ERNST & YOUNG': 'Consulting',
  'EY': 'Consulting',
  'PRICEWATERHOUSECOOPERS': 'Consulting',
  'PWC': 'Consulting',
  'KPMG': 'Consulting',
  'ACCENTURE': 'Consulting',
  'OLIVER WYMAN': 'Consulting',
  'BAIN & COMPANY': 'Consulting',
  'A.T. KEARNEY': 'Consulting',

  // Transportation
  'UNITED AIRLINES': 'Transportation',
  'AMERICAN AIRLINES': 'Transportation',
  'DELTA AIR LINES': 'Transportation',
  'SOUTHWEST AIRLINES': 'Transportation',
  'JETBLUE': 'Transportation',
  'AMTRAK': 'Transportation',
  'CSX': 'Transportation',
  'NORFOLK SOUTHERN': 'Transportation',
  'UNION PACIFIC': 'Transportation',
  'FEDEX': 'Transportation',
  'UPS': 'Transportation',
  'DHL': 'Transportation',

  // Retail & Commerce
  'WALMART': 'Retail & Commerce',
  'TARGET': 'Retail & Commerce',
  'HOME DEPOT': 'Retail & Commerce',
  'COSTCO': 'Retail & Commerce',
  "MACY'S": 'Retail & Commerce',
  'NORDSTROM': 'Retail & Commerce',
  'WALGREENS': 'Retail & Commerce',
  'KROGER': 'Retail & Commerce',
  'WHOLE FOODS MARKET': 'Retail & Commerce',
}

const INDUSTRY_KEYWORD_PATTERNS: { pattern: RegExp; industry: string }[] = [
  { pattern: /INVEST|ASSET MGMT|HEDGE FUND|PRIVATE EQUITY/, industry: 'Investment & Private Equity' },
  { pattern: /BANK|FINANCIAL|FINANCE|CREDIT UNION|MORTGAGE|BROKERAGE|SECURITIES/, industry: 'Finance & Banking' },
  { pattern: /\bLAW\b|LLP|ATTORNEYS|LEGAL|COUNSEL|SOLICITORS/, industry: 'Law' },
  { pattern: /REALT|REAL ESTATE|HOMEBUIL/, industry: 'Real Estate' },
  { pattern: /PHARMA|BIOTECH|BIOSCIENCE|THERAPEUTICS|GENOMICS/, industry: 'Pharmaceuticals' },
  { pattern: /HEALTH|HOSPITAL|MEDICAL|CLINIC|DENTAL|SURGERY/, industry: 'Healthcare' },
  { pattern: /TECH|SOFTWARE|DIGITAL|CYBER|CLOUD|PLATFORM/, industry: 'Technology' },
  { pattern: /ENERGY|OIL|GAS|PETROLEUM|POWER|ELECTRIC|UTILITY|SOLAR|WIND/, industry: 'Energy' },
  { pattern: /DEFENSE|AEROSPACE|ARMAMENT/, industry: 'Defense' },
  { pattern: /UNIVERSITY|COLLEGE|SCHOOL|ACADEMY|INSTITUTE OF/, industry: 'Education' },
  { pattern: /MEDIA|BROADCAST|PUBLISH|ENTERTAINMENT|STUDIO|FILM|TELEVISION/, industry: 'Media & Entertainment' },
  { pattern: /AIRLINE|AIRWAYS|RAIL|RAILROAD|SHIPPING|TRANSPORT|LOGISTICS/, industry: 'Transportation' },
  { pattern: /CONSULT|ADVISORY|MANAGEMENT SOLUTIONS/, industry: 'Consulting' },
  { pattern: /HOTEL|RESORT|HOSPITALITY|RESTAURANT|FOOD SERVICE/, industry: 'Hospitality & Food' },
  { pattern: /CAPITAL/, industry: 'Investment & Private Equity' },
  { pattern: /GOVERNMENT|FEDERAL|STATE OF |COUNTY OF |CITY OF |DEPT OF /, industry: 'Government & Public Sector' },
]

// Maps FEC/employer industry categories to bill topic slugs for pre-filtering
// donor relevance before calling the LLM. Empty array = too broad to pre-filter.
export const INDUSTRY_TO_TOPICS: Record<string, string[]> = {
  'Energy':                       ['climate-environment', 'economy-jobs'],
  'Healthcare':                   ['healthcare'],
  'Pharmaceuticals':              ['healthcare'],
  'Technology':                   ['tech-privacy', 'economy-jobs'],
  'Finance & Banking':            ['economy-jobs'],
  'Investment & Private Equity':  ['economy-jobs'],
  'Defense':                      ['foreign-policy'],
  'Education':                    ['education'],
  'Real Estate':                  ['housing', 'economy-jobs'],
  'Media & Entertainment':        ['tech-privacy'],
  'Transportation':               ['economy-jobs'],
  'Consulting':                   [],
  'Law':                          [],
  'Government & Public Sector':   [],
  'Hospitality & Food':           ['economy-jobs'],
  'Various':                      [],
}

export function getEmployerIndustry(rawUppercaseName: string): string {
  const key = rawUppercaseName.toUpperCase().trim()
  if (EMPLOYER_INDUSTRY_MAP[key]) return EMPLOYER_INDUSTRY_MAP[key]
  for (const { pattern, industry } of INDUSTRY_KEYWORD_PATTERNS) {
    if (pattern.test(key)) return industry
  }
  return 'Various'
}
