/**
 * `/bills/[id]` — bill detail view.
 *
 * Dynamic metadata is generated by the sibling `layout.tsx`; this file is
 * just the entry point into the client component that renders the page.
 */

export { default } from '@/components/bills/BillDetailPage'
